const mongoose = require('mongoose')
const Schema = mongoose.Schema
const {monthlyIncome, employment, wadiah, amanah, mudarabah, fyc, fixedTime, savingAccount,
    banks, currency, kinGender, statement, statementDuration,
    homeType,maritalStatus, accountStatus, language, gender,
    identification,cardType,electronicBanking, transactionAlert, chequeCategory, advertisement,
 }= require('../constants/const');

const UserSchema = new Schema({
    wadiah:{
        type:String,
        enum:wadiah
    },
    amanah:{
        type:String,
        enum:amanah
    },
    mudarabah:{
        type:String,
        enum:mudarabah
    },
    fyc:{
        type:String,
        enum:fyc
    },
    fixedTime:{
        type:String,
        enum:fixedTime
    },
    savingAccount:{
        type:String,
        enum:savingAccount
    },
    joint:{
        type:String,
    },
    fixed:{
        type:String,
    },
    currency:{
        type:String,
        enum:currency
    },
    otherType:{type:String},
    title:{type:String},
    fullName:{type:String},
    birthPlace:{type:String},
    childrenNo:{type:Number},
    dependents:{type:Number},
    motherName:{type:String},
    nationality:{type:String},
    permitNo:{type:Number},
    date:{type:Date},
    purpose:{type:String},
    maritalStatus:{
        type:String,
        enum:maritalStatus
    },
    gender:{
        type:String,
        enum:gender
    },
    country:{type:String},
    region:{type:String},
    city:{type:String},
    subCity:{type:String},
    kebele:{type:Number},
    hNo:{type:Number},
    telNo:{type:Number},
    email:{type:String},
    poBox:{type:String},
    homeType:{
        type:String,
        enum:homeType
    },
    identification:{
        type:String,
        enum:identification
    },
    idNo:{type:Number},
    idIssued:{type:Date},
    expiredDate:{type:Date},
    cardType:{
        type:String,
        enum:cardType
    },
    electronicBanking:{
        type:String,
        enum:electronicBanking
    },
    transactionAlert:{
        type:String,
        enum:transactionAlert
    },
    statement:{
        type:String,
        enum:statement
    },
    statementDuration:{
        type:String,
        enum:statementDuration
    },
    chequeCategory:{
        type:String,
        enum:chequeCategory
    },
    chequeAmount:{type:Number},
    employment:{
        type:String,
        enum:employment
    },
    monthlyIncome:{
        type:String,
        enum:monthlyIncome
    },
    specify:{type:Number},
    annualIncome:{type:Number},
    employer:{type:String},
    profession:{type:String},
    kinTitle:{type:String},
    kinFullName:{type:String},
    kinDate:{type:Date},
    kinGender:{
        type:String,
        enum:kinGender
    },
    kinRelationship:{type:String},
    kinTelNo:{type:Number},
    kinHouseNo:{type:Number},
    kinEmail:{type:String},
    kinCountry:{type:String},
    kinRegion:{type:String},
    kinCity:{type:String},
    kinSubCity:{type:String},
    kinKebele:{type:Number},
    kinHNo:{type:Number},
    banks:{
        type:String,
        enum:banks
    },
    accountName:{type:String},
    accountNumber:{type:Number},
    accountStatus:{
        type:String,
        enum:accountStatus
    },
    language:{
        type:String,
        enum:language
    },
    advertisement:{
        type:String,
        enum:advertisement
    },
    thirdParty:{
        type:String,
    },
    interpreterName:{type:String},
    interpreterAddress:{type:String},
    interpreterTelNo:{type:String},
    agreed:{
        type:String,
    },
    abaAccountNumber:{type:Number},
    })
    module.exports = mongoose.model('User', UserSchema, 'user');
